/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_davidhs_fmtest_NativeMIDIFile_MidiEvent */

#ifndef _Included_com_davidhs_fmtest_NativeMIDIFile_MidiEvent
#define _Included_com_davidhs_fmtest_NativeMIDIFile_MidiEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
