/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_davidhs_fmtest_NativeFMSynth */

#ifndef _Included_com_davidhs_fmtest_NativeFMSynth
#define _Included_com_davidhs_fmtest_NativeFMSynth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_davidhs_fmtest_NativeFMSynth
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_davidhs_fmtest_NativeFMSynth_init
  (JNIEnv *, jobject);

/*
 * Class:     com_davidhs_fmtest_NativeFMSynth
 * Method:    write
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_com_davidhs_fmtest_NativeFMSynth_write
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     com_davidhs_fmtest_NativeFMSynth
 * Method:    getsamples
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_com_davidhs_fmtest_NativeFMSynth_getsamples
  (JNIEnv *, jobject, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
