/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_davidhs_fmtest_NativeMIDIFile */

#ifndef _Included_com_davidhs_fmtest_NativeMIDIFile
#define _Included_com_davidhs_fmtest_NativeMIDIFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile
 * Method:    midifile_open
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_midifile_1open__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile
 * Method:    midifile_open
 * Signature: (Ljava/io/InputStream;)J
 */
JNIEXPORT jlong JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_midifile_1open__Ljava_io_InputStream_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile
 * Method:    midifile_read
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_midifile_1read
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile
 * Method:    midifile_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_midifile_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile
 * Method:    midifile_getTrackCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_midifile_1getTrackCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile
 * Method:    midifile_getTrack
 * Signature: (JI)Lcom/davidhs/fmtest/NativeMIDIFile/MidiEventList;
 */
JNIEXPORT jobject JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_midifile_1getTrack
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile
 * Method:    midifile_getTicksPerQuarterNote
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_midifile_1getTicksPerQuarterNote
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
