/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_davidhs_fmtest_NativeMIDIFile_MidiEventList */

#ifndef _Included_com_davidhs_fmtest_NativeMIDIFile_MidiEventList
#define _Included_com_davidhs_fmtest_NativeMIDIFile_MidiEventList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_davidhs_fmtest_NativeMIDIFile_MidiEventList
 * Method:    midifile_getTrack_get
 * Signature: (JII)Lcom/davidhs/fmtest/NativeMIDIFile/MidiEvent;
 */
JNIEXPORT jobject JNICALL Java_com_davidhs_fmtest_NativeMIDIFile_00024MidiEventList_midifile_1getTrack_1get
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
